import Footer from '@/Components/Footer/Footer'
import Intro from '@/Components/Sections/Intro/Intro'
import SocialMedia from '@/Components/Sections/Social/SocialMedia'
import About from '@/Components/Sections/about/About'
import Contact from '@/Components/Sections/contact/Contact'
import Portfolio from '@/Components/Sections/portfolio/Portfolio'
import Pricing from '@/Components/Sections/pricing/Pricing'
import Reasons from '@/Components/Sections/reason/Reasons'
import Topbar from '@/Components/Topbar/Topbar'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>OnBeirut | Web Development Agency</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta httpEquiv="content-language" content="en"/>
  <meta charSet="UTF-8"/>
  <meta name="keywords" content="web development, agency, lebanon, beirut, web desgin, SEO"/>
  <meta name="description" content="This short description describes my website."/>
  <meta name="page-topic" content="Web Development"/>
  <meta name="page-type" content="Web Development"/>
  <meta name="audience" content="Everyone"/>
  <meta name="robots" content="index, follow"/>
  <meta property="og:site_name" content="OnBeirut"/>
      </Head>
      <Topbar/>
      <main>
      <Intro/>
      <SocialMedia/>
      <About/>
      <Reasons/>
      <Portfolio/>
      <Pricing/>
      <Contact/>
      <Footer/>
  
      </main>
    </>
  )
}
